INSERT INTO address (lines, city, country, postcode)
    VALUES ('The White Chapel Building, 10 Whitechapel High St', 'London', 'United Kingdom', 'E1 8DX'),
           ('60 Truax Hill', 'Swindon', 'United Kingdom', 'SN1 0ZZ'),
           ('048 Heffernan Alley', 'Church End', 'United Kingdom', 'CB4 0ZZ'),
           ('2 Mcguire Center', 'Swindon', 'United Kingdom', 'SN2 0ZZ'),
           ('0966 School Point', 'Liverpool', 'United Kingdom', 'L74 0ZZ'),
           ('60563 Bowman Drive', null, 'United Kingdom', 'G4 0ZZ'),
           ('056 Dayton Way', 'Horton', 'United Kingdom', 'BS37 0ZZ'),
           ('0 Scoville Circle', 'Middleton', 'United Kingdom', 'LE16 0ZZ'),
           ('4164 Ilene Terrace', 'Kinloch', 'United Kingdom', 'PH43 0ZZ'),
           ('9 Oakridge Court', 'Tullich', 'United Kingdom', 'AB55 0ZZ'),
           ('690 Garrison Pass', 'Pentre', 'United Kingdom', 'SY4 0ZZ'),
           ('950 Carpenter Lane', 'Edinburgh', 'United Kingdom', 'EH9 0ZZ'),
           ('46510 Tony Drive', null, 'United Kingdom', 'OX12 0ZZ'),
           ('40 Hoepker Drive', 'Birmingham', 'United Kingdom', 'B40 0ZZ'),
           ('59 3rd Alley', 'Ashley', 'United Kingdom', 'SN13 0ZZ'),
           ('36150 Bluejay Avenue', 'Ford', 'United Kingdom', 'GL54 0ZZ'),
           ('9 Scoville Point', 'Preston', 'United Kingdom', 'PR1 0ZZ'),
           ('95 Butterfield Hill', 'Hatton', 'United Kingdom', 'CV35 0ZZ'),
           ('1062 Pearson Avenue', 'Stapleford', 'United Kingdom', 'LN6 0ZZ'),
           ('2248 Nobel Place', 'Kingston', 'United Kingdom', 'DT10 0ZZ'),
           ('1 Steensland Trail', null, 'United Kingdom', 'CT15 0ZZ'),
           ('08231 Burrows Pass', 'Carlton', 'United Kingdom', 'DL8 0ZZ'),
           ('8840 2nd Terrace', 'Ashley', 'United Kingdom', 'SN14 0ZZ');

INSERT INTO address (lines, city, country, international_postcode)
    VALUES ('Square Ambiorix', 'Bruxelles', 'Belgium', '1000'),
           ('Broerstraat 5', 'Groningen', 'The Netherlands', '9712 CP');

INSERT INTO person (first_name, middle_name, surname, address, date_of_birth)
    VALUES ('Joe', null, 'Bloggs', (SELECT address_id FROM address WHERE postcode = 'E1 8DX'), '1970-01-01'),
           ('Karl', null, 'Delacroux', (SELECT address_id FROM address WHERE postcode = 'SN1 0ZZ'), '1949-04-02'),
           ('Elizabeth', null, 'Pettican', (SELECT address_id FROM address WHERE postcode = 'CB4 0ZZ'), '1993-08-26'),
           ('Ann-marie', 'Dari', 'Stit', (SELECT address_id FROM address WHERE postcode = 'SN2 0ZZ'), '1976-11-20'),
           ('Tom', null, 'Attewell', (SELECT address_id FROM address WHERE postcode = 'L74 0ZZ'), '1935-10-22'),
           ('Anya', 'Melissa', 'Irwin', (SELECT address_id FROM address WHERE postcode = 'G4 0ZZ'), '1966-12-18'),
           ('Jon', 'Ives', 'Dowbiggin', (SELECT address_id FROM address WHERE postcode = 'BS37 0ZZ'), '1958-03-31'),
           ('Gregory', 'Charles', 'McMillan', (SELECT address_id FROM address WHERE postcode = 'LE16 0ZZ'), '1969-10-30'),
           ('Jennifer', null, 'Ralestone', (SELECT address_id FROM address WHERE postcode = 'PH43 0ZZ'), '1991-04-01'),
           ('Franciska', 'Ave', 'Castilljo', (SELECT address_id FROM address WHERE postcode = 'AB55 0ZZ'), '1952-11-27'),
           ('Paul', null, 'Adin', (SELECT address_id FROM address WHERE postcode = 'SY4 0ZZ'), '1962-06-10'),
           ('Moyra', 'Dari', 'Bourhill', (SELECT address_id FROM address WHERE postcode = 'EH9 0ZZ'), '1954-08-13'),
           ('Suzanne', null, 'Nassy', (SELECT address_id FROM address WHERE postcode = 'OX12 0ZZ'), '1935-03-25'),
           ('Charles', 'Dori', 'Petrashkov', (SELECT address_id FROM address WHERE postcode = 'B40 0ZZ'), '1955-08-31'),
           ('Tami', null, 'Dorgan', (SELECT address_id FROM address WHERE postcode = 'SN13 0ZZ'), '1998-08-27'),
           ('Irena', null, 'Norval', (SELECT address_id FROM address WHERE postcode = 'GL54 0ZZ'), '1955-01-31'),
           ('Peter', 'David', 'Dimmock', (SELECT address_id FROM address WHERE postcode = 'PR1 0ZZ'), '1932-06-06'),
           ('Antonia', null, 'Devons', (SELECT address_id FROM address WHERE postcode = 'CV35 0ZZ'), '1984-04-07'),
           ('Rachel', null, 'Sambells', (SELECT address_id FROM address WHERE postcode = 'LN6 0ZZ'), '1943-05-28'),
           ('Hagen', 'Nessa', 'Corbishley', (SELECT address_id FROM address WHERE postcode = 'DT10 0ZZ'), '1954-09-04'),
           ('Hannah', 'Kate', 'Barnham', (SELECT address_id FROM address WHERE postcode = 'CT15 0ZZ'), '1937-03-11'),
           ('Daniel', 'Timothy', 'Roke', (SELECT address_id FROM address WHERE postcode = 'DL8 0ZZ'), '1986-06-28'),
           ('Eirlys', 'Nancy', 'Fautley', (SELECT address_id FROM address WHERE postcode = 'SN14 0ZZ'), '1968-01-14'),
           ('Vic', null, 'Strahan', (SELECT address_id FROM address WHERE international_postcode = '1000'), '1978-11-15'),
           ('Arlin', 'Nomi', 'Valens-Smith', (SELECT address_id FROM address WHERE international_postcode = '9712 CP'), '1993-08-11');